### ISSUE TITLE
Use realtime UDP API instead of JSON API for animations

### ISSUE THREAD

**Issue by ChuckMash** [michaeljvdh/WledGetPixy#3]
Great project!
I'm looking forward to digging into this a bit more in the future.

Right off the bat, it looks like push.py is using the WLED JSON API to update the LED state.
Please ignore if I am mistaken.

Have you considered using one of the other more streamlined APIs?
https://kno.wled.ge/interfaces/udp-realtime/

The end result should be a faster update / smoother animation with a smaller network footprint.

Cheers!

**Comment by michaeljvdh** [comment]
Yes @ChuckMash and there are some issues in regard to how big the payload can be, 16x16 and less is easy to deal with, beyond that is problematic, and ultimately would require multiple controllers in say 256 pixel segments.  But we have ideas and a way to address the problem.  Consider this version as the best solution for the general DIY guy, and likely the simplest method for pictures period.  Thanks for the feedback.

**Comment by michaeljvdh** [comment]
Will looking to DNRGB I am aware of it, but didn't realize the start index. As for serial, definitely not going down that route.

Really appreciate your insight and response.
